830 : Add metadata_version sequence and column in settings_metadata t…
opensrp/opensrp-server-configs pull request #126
Opened 2021-05-24 14:13 UTC by rehammuzzamil

…able

https://github.com/opensrp/opensrp-server-web/issues/830

2021-05-25 07:21 UTC, bennsimon requested changes
@rehammuzzamil How is update handled? Shouldnt it update the `metadata_version` for that record.

2021-05-25 12:01 UTC, rehammuzzamil commented
> @rehammuzzamil How is update handled? Shouldnt it update the `metadata_version` for that record.

@bennsimon updates are catered on the server-core, whenever a new record is added or an already existing record is updated in the settings_metadata table, an increment is done on the metadata_version column through :
` metadata_version =  nextVal('core.setting_metadata_version_seq')`
It is the same approach as per the server_version.

Please let me know if there is anything incorrect.

2021-05-26 12:47 UTC, bennsimon requested changes

2021-05-26 12:47 UTC, bennsimon commented on assets/migrations/scripts/20210520084102_add_metadata_version_in_settings_metadata_table.sql
> +ALTER TABLE core.settings_metadata ADD COLUMN metadata_version bigint DEFAULT nextval('core.setting_metadata_version_seq');
```suggestion
ALTER TABLE core.settings_metadata ADD COLUMN IF NOT EXISTS metadata_version bigint DEFAULT nextval('core.setting_metadata_version_seq');
```

2021-05-26 12:58 UTC, bennsimon approved these changes

2021-05-26 13:01 UTC, merged