Initialize the anc test data update stored procedure
opensrp/opensrp-server-configs pull request #127
Opened 2021-05-25 07:40 UTC by dubdabasoduba

2021-05-28 09:06 UTC, allan-on requested changes
Noted that: 
`core.client json->>'dateEdited'` and `json->>'dateCreated'` aren't being updated though the 
`client_metadata.date_created`, `client_metadata.date_edited` are updated. 
These should be synced

2021-06-08 12:07 UTC, bennsimon commented
Before
````json
{"_id": "4cfa765a-fab0-46d0-b0ef-f0c6334677d7", "obs": [], "_rev": "v1", "team": "Bukesa", "type": "Event", "teamId": "6c8d2b9b-2246-47c2-949b-4fe29e888cc8", "details": {"Contact": "Contact 2", "open_test_tasks": "[\"{\\\"key\\\":\\\"accordion_blood_haemoglobin\\\",\\\"openmrs_entity_parent\\\":\\\"\\\",\\\"openmrs_entity\\\":\\\"\\\",\\\"openmrs_entity_id\\\":\\\"\\\",\\\"text\\\":\\\"Blood Haemoglobin test\\\",\\\"accordion_info_text\\\":\\\"Blood haemoglobin testing is necessary for diagnosing anaemia in pregnancy.\\\",\\\"accordion_info_title\\\":\\\"Blood haemoglobin test\\\",\\\"type\\\":\\\"expansion_panel\\\",\\\"content_form\\\":\\\"tests_blood_haemoglobin_sub_form\\\",\\\"container\\\":\\\"anc_test\\\",\\\"relevance\\\":{\\\"rules-engine\\\":{\\\"ex-rules\\\":{\\\"rules-file\\\":\\\"tests_expansion_panel_relevance_rules.yml\\\"}}},\\\"is_visible\\\":true}\",\"{\\\"key\\\":\\\"accordion_urine\\\",\\\"openmrs_entity_parent\\\":\\\"\\\",\\\"openmrs_entity\\\":\\\"\\\",\\\"openmrs_entity_id\\\":\\\"\\\",\\\"text\\\":\\\"Urine test\\\",\\\"accordion_info_text\\\":\\\"A urine test is required at the first contact, last contact in 2nd trimester, and 2nd contact in 3rd trimester OR anytime the woman reports pain during urination (dysuria). A dipstick test is required if the woman has a repeat high BP reading (140\\\\\\/90 or higher). Otherwise, a urine test is optional. The urine test checks for bacterial or other infections that can lead to adverse outcomes for the neonate. The urine dipstick test can check for proteins in the urine, which can be a sign of pre-eclampsia.\\\",\\\"accordion_info_title\\\":\\\"Urine test\\\",\\\"type\\\":\\\"expansion_panel\\\",\\\"content_form\\\":\\\"tests_urine_sub_form\\\",\\\"container\\\":\\\"anc_test\\\",\\\"relevance\\\":{\\\"rules-engine\\\":{\\\"ex-rules\\\":{\\\"rules-file\\\":\\\"tests_expansion_panel_relevance_rules.yml\\\"}}},\\\"is_visible\\\":true}\",\"{\\\"key\\\":\\\"accordion_syphilis\\\",\\\"openmrs_entity_parent\\\":\\\"\\\",\\\"openmrs_entity\\\":\\\"\\\",\\\"openmrs_entity_id\\\":\\\"\\\",\\\"text\\\":\\\"Syphilis test\\\",\\\"accordion_info_text\\\":\\\"A syphilis test is recommended for all pregnant women at the first contact and again at the first contact of 3rd trimester (28 weeks).\\\",\\\"accordion_info_title\\\":\\\"Syphilis test\\\",\\\"type\\\":\\\"expansion_panel\\\",\\\"content_form\\\":\\\"tests_syphilis_sub_form\\\",\\\"container\\\":\\\"anc_test\\\",\\\"relevance\\\":{\\\"rules-engine\\\":{\\\"ex-rules\\\":{\\\"rules-file\\\":\\\"tests_expansion_panel_relevance_rules.yml\\\"}}},\\\"is_visible\\\":true}\",\"{\\\"key\\\":\\\"accordion_hepatitis_c\\\",\\\"openmrs_entity_parent\\\":\\\"\\\",\\\"openmrs_entity\\\":\\\"\\\",\\\"openmrs_entity_id\\\":\\\"\\\",\\\"text\\\":\\\"Hepatitis C test\\\",\\\"accordion_info_text\\\":\\\"In settings where the proportion of HCV antibody seroprevalence in the general population is 2% or higher, or the woman is HIV positive, injects drugs, or is a sex worker, then a Hep C test is required.\\\",\\\"accordion_info_title\\\":\\\"Hepatitis C test\\\",\\\"type\\\":\\\"expansion_panel\\\",\\\"content_form\\\":\\\"tests_hepatitis_c_sub_form\\\",\\\"container\\\":\\\"anc_test\\\",\\\"relevance\\\":{\\\"rules-engine\\\":{\\\"ex-rules\\\":{\\\"rules-file\\\":\\\"tests_expansion_panel_relevance_rules.yml\\\"}}},\\\"is_visible\\\":true}\",\"{\\\"key\\\":\\\"accordion_ultrasound\\\",\\\"openmrs_entity_parent\\\":\\\"\\\",\\\"openmrs_entity\\\":\\\"\\\",\\\"openmrs_entity_id\\\":\\\"\\\",\\\"text\\\":\\\"Ultrasound test\\\",\\\"accordion_info_text\\\":\\\"An ultrasound is recommended for all women before 24 weeks gestation or even after if deemed necessary (e.g. to identify the number of fetuses, fetal presentation, or placenta location).\\\",\\\"accordion_info_title\\\":\\\"Ultrasound test\\\",\\\"type\\\":\\\"expansion_panel\\\",\\\"content_form\\\":\\\"tests_ultrasound_sub_form\\\",\\\"container\\\":\\\"anc_test\\\",\\\"relevance\\\":{\\\"rules-engine\\\":{\\\"ex-rules\\\":{\\\"rules-file\\\":\\\"tests_expansion_panel_relevance_rules.yml\\\"}}},\\\"is_visible\\\":true}\"]", "previous_contacts": "{\"contact_date\":\"2021-03-22\",\"attention_flag_facts\":\"{\\\"condom_use_value\\\":\\\"Yes\\\",\\\"isRelevant\\\":false,\\\"abdominal_exam_value\\\":\\\"Not done\\\",\\\"select_gest_age_edd_lmp_ultrasound\\\":\\\"0\\\",\\\"pregest_weight\\\":\\\"45\\\",\\\"oedema_value\\\":\\\"No\\\",\\\"flu_immun_status\\\":\\\"seasonal_flu_dose_missing\\\",\\\"select_gest_age_edd\\\":\\\"ultrasound\\\",\\\"medications\\\":\\\"[none]\\\",\\\"ipv_clinical_enquiry_not_done_reason\\\":\\\"other\\\",\\\"tt1_date\\\":\\\"done_today\\\",\\\"height\\\":\\\"150\\\",\\\"cardiac_exam\\\":\\\"1\\\",\\\"hiv_test_date_today_hidden\\\":\\\"22-03-2021\\\",\\\"shs_exposure\\\":\\\"no\\\",\\\"eat_exercise_counsel\\\":\\\"done\\\",\\\"calcium_supp\\\":\\\"done\\\",\\\"preeclampsia\\\":\\\"0\\\",\\\"lmp_known_value\\\":\\\"No\\\",\\\"toaster26_hidden\\\":\\\"0\\\",\\\"no_of_fetuses\\\":\\\"1\\\",\\\"blood_type_test_date\\\":\\\"22-03-2021\\\",\\\"other_symptoms_value\\\":\\\"None\\\",\\\"health_conditions_value\\\":\\\"None\\\",\\\"malaria_counsel_value\\\":\\\"Done\\\",\\\"danger_signs_value\\\":\\\"None\\\",\\\"abdominal_exam\\\":\\\"1\\\",\\\"surgeries_value\\\":\\\"None\\\",\\\"ipv_signs_symptoms_value\\\":\\\"No presenting signs or symptoms indicative of IPV\\\",\\\"tt1_date_done_date_today_hidden\\\":\\\"22-03-2021\\\",\\\"vita_supp\\\":\\\"done\\\",\\\"ultrasound_gest_age_wks\\\":\\\"13\\\",\\\"health_conditions\\\":\\\"[none]\\\",\\\"vita\\\":\\\"Vitamin A supplement\\\",\\\"ultrasound_done_value\\\":\\\"Yes\\\",\\\"tobacco_user\\\":\\\"no\\\",\\\"exp_weight_gain\\\":\\\"11.5 - 16\\\",\\\"pulse_rate\\\":\\\"80\\\",\\\"sp\\\":\\\"Sulfadoxine-pyrimethamine (SP) for malaria prevention\\\",\\\"pallor_value\\\":\\\"No\\\",\\\"caffeine_intake\\\":\\\"[none]\\\",\\\"hiv_test_date\\\":\\\"22-03-2021\\\",\\\"hbsag_lab_ima\\\":\\\"positive\\\",\\\"alcohol_substance_counsel\\\":\\\"done\\\",\\\"pallor\\\":\\\"no\\\",\\\"breast_exam_value\\\":\\\"Not done\\\",\\\"yes_value\\\":\\\"22-03-2021\\\",\\\"antibiotic\\\":\\\"0\\\",\\\"gdm_risk\\\":\\\"0\\\",\\\"ifa_low_prev_value\\\":\\\"Done\\\",\\\"breast_exam\\\":\\\"1\\\",\\\"miscarriages_abortions\\\":\\\"0\\\",\\\"hiv_test_status_value\\\":\\\"Done today\\\",\\\"hepb_test_status_value\\\":\\\"Done today\\\",\\\"helper\\\":null,\\\"flu_date\\\":\\\"done_today\\\",\\\"cervical_exam_value\\\":\\\"Not done\\\",\\\"iptp_sp1_dose_number\\\":\\\"1\\\",\\\"blood_type_test_status_value\\\":\\\"Done today\\\",\\\"hiv_test_status\\\":\\\"done_today\\\",\\\"alcohol_substance_enquiry_value\\\":\\\"No\\\",\\\"phys_symptoms\\\":\\\"[none]\\\",\\\"iptp_sp3_dose_number\\\":\\\"0\\\",\\\"respiratory_exam\\\":\\\"1\\\",\\\"weight_cat\\\":\\\"Normal Weight\\\",\\\"hiv_positive\\\":\\\"1\\\",\\\"fetal_heartbeat\\\":\\\"yes\\\",\\\"bp_systolic\\\":\\\"120\\\",\\\"hepb_test_type_value\\\":\\\"HBsAg laboratory-based immunoassay (recommended)\\\",\\\"first_weight\\\":\\\"45\\\",\\\"tt_immun_status_value\\\":\\\"No doses\\\",\\\"lmp_gest_age\\\":\\\"0\\\",\\\"ifa_low_prev\\\":\\\"done\\\",\\\"iptp_sp1_value\\\":\\\"Done\\\",\\\"lmp_known\\\":\\\"no\\\",\\\"allergies\\\":\\\"[none]\\\",\\\"preeclampsia_risk\\\":\\\"0\\\",\\\"partner_hiv_positive\\\":\\\"0\\\",\\\"hiv_positive_counsel_value\\\":\\\"Done\\\",\\\"alcohol_substance_use\\\":\\\"[cocaine]\\\",\\\"alcohol_substance_use_value\\\":\\\"Cocaine\\\",\\\"parity\\\":\\\"1\\\",\\\"partner_hiv_status\\\":\\\"negative\\\",\\\"malaria_counsel\\\":\\\"done\\\",\\\"contact_reason\\\":\\\"first_contact\\\",\\\"ultrasound_gest_age_concept\\\":\\\"0\\\",\\\"rh_factor_value\\\":\\\"Positive\\\",\\\"ultrasound_done\\\":\\\"yes\\\",\\\"educ_level\\\":\\\"none\\\",\\\"ultrasound_gest_age_selection\\\":\\\"ultrasound\\\",\\\"live_births\\\":\\\"1\\\",\\\"ifa\\\":\\\"Iron &amp; folic acid supplement\\\",\\\"yes\\\":\\\"[22-03- [...]

2021-06-16 14:31 UTC, allan-on commented
```sql 
SELECT json->>'dateEdited' FROM core.client; --> Not edited
         ?column?         
--------------------------
 2021-03-23T15:46:22.912Z

SELECT json->>'dateCreated' FROM core.client; --> Not edited
         ?column?         
--------------------------
 2021-03-22T09:25:51.438Z
 ```
 @bennsimon @dubdabasoduba These values aren't being updated. Should they?

2021-06-16 15:13 UTC, allan-on commented
We fixed updating `core.client` `dateEdited` and `dateCreated` with @bennsimon ✅ 
The only remaining issue now appears to be updating of `core.client` **attributes**
```sql 
SELECT json->>'attributes' FROM core.client;
```
**EDD** and c**ontact dates** aren't being updated ❌

2021-06-17 09:57 UTC, dubdabasoduba commented
> ```sql
> SELECT json->>'dateEdited' FROM core.client; --> Not updated
>          ?column?         
> --------------------------
>  2021-03-23T15:46:22.912Z
> 
> SELECT json->>'dateCreated' FROM core.client; --> Not updated
>          ?column?         
> --------------------------
>  2021-03-22T09:25:51.438Z
> ```
> 
> @bennsimon @dubdabasoduba These values aren't being updated. Should they?

Yes they should.

2021-06-17 09:57 UTC, dubdabasoduba commented
> We fixed updating `core.client` `dateEdited` and `dateCreated` with @bennsimon 
> The only remaining issue now appears to be updating of `core.client` **attributes**
> 
> ```sql
> SELECT json->>'attributes' FROM core.client;
> ```
> 
> **EDD** and c**ontact dates** aren't being updated

This should be updated too.

2021-06-18 10:42 UTC, allan-on commented on assets/server-scripts/anc_test_data_update_stored_procedure.sql
> +        to_timestamp(server_version) + CAST(counter as interval)));
It appears there was a missing migration. This has been addressed ✔️

2021-06-18 10:42 UTC, allan-on commented on assets/server-scripts/anc_test_data_update_stored_procedure.sql
> +        to_timestamp(server_version / 1000 :: bigint) + CAST(counter as interval))) * 1000;
It appears there was a missing migration. This has been addressed ✔️

2021-06-18 11:08 UTC, allan-on approved these changes

2021-06-18 11:14 UTC, merged