Update the properties to add a dhis2 <> opensrp keycloak check
opensrp/opensrp-server-configs pull request #142
Opened 2021-12-16 00:31 UTC by dubdabasoduba

:necktie:Update the dhis2 properties to add a property to check wheth…er the OpenSRP instance uses keycloak

2021-12-22 02:23 UTC, AndreLesa approved these changes

2022-01-24 06:13 UTC, bennsimon requested changes

2022-01-24 06:13 UTC, bennsimon commented on assets/config/opensrp.properties
> +dhis2.keycloak.location=true
needs to be false

2022-01-26 12:07 UTC, bennsimon approved these changes

2022-01-26 12:08 UTC, merged